### ISSUE TITLE
src/model/dti_sprites.py, there is no self.occ_noise

### ISSUE THREAD

**Issue by actruce** [monniert/dti-sprites#1]
Hello!
When I debug the trainer.py with config=dsprites.yml, there was an error

It's about missing self.occ_noise code at all in
**if self.occ_noise > 0 and self.training: (247 line in model/dti_sprites.py)**

If you can find any mistakes, please modify and notice about that.
Thanx

**Comment by monniert** [comment]
Hi, thanks for raising the issue, it was indeed a small block of code from previous experiments.

The dsprites.yml experiments should run smoothly now, let me know if you run into other issues
