### ISSUE TITLE
morphological transformation for RGB sprites?

### ISSUE THREAD

**Issue by ahnchive** [monniert/dti-sprites#3]
Hi -- First, thanks for putting up the code and material here. It's very interesting work and this code repo has been great of help to understand your model.

While I'm experimenting with your codes, I noticed that the current implementation of morphological transformation does not work with color sprites. It gives a size mismatch in the first dimension of sprites and alpha/kernel tensors which have B instead of B*C that sprites have. Just wonder if there's any workaround this.

Also, can you provide little more details on how the dataset is generated? especially the mask labels? I'm trying to run the model on overlapping mnist dataset (as shown in your pipeline figure, but it give me a warning like below:
`WARN InstanceSegScores._fast_hist error: labels in GT are greater than nb instances`

Any input will be appreciated! Thank you very much.

**Comment by monniert** [comment]
Hi @ahnchive, thanks for the interest in the project!

1. indeed, the morphological module comes from the prior clustering work (https://github.com/monniert/dti-clustering) and was defined for grayscale images only; I think extending it to RGB images could be interesting but is not trivial as I am not sure about the desired output

2. Sure, basically in your case, inside a `datasets/multi_mnist` folder, you should create for each data point:
- the input image into a `images` folder
- the semantic mask (from 0 to 9 per-pixel labels) into a `sem_masks` folder
- the instance mask (from 0 for bkg to N_max per-pixel labels, N_max being the max number of objects per image) into a `masks` folder

Then you can reuse the abstract dataloader from `src/datasets/multi_objects.py` to create a new one pointing towards `multi_mnist`. You should download one of the multi-object datasets like the tetrominoes for a good example

**Comment by ahnchive** [comment]
Thank you for your quick reply and clarifications, @monniert!

I was able to create the dataset as you explained and the model works like a charm under overlapping digits! Freezing sprites for one epoch + add pooling layer to the encoder + have similarity_tps as sprite transformation seem to be the best setup for this task (it helps recovering all 10 digit sprites correctly), but please advise me if there's any better configs available for digit experiments you know from your experience.

I will close this issue as it was resolved.
